"""followers

Revision ID: 473aa203d910
Revises: 4d872a008e19
Create Date: 2022-08-29 20:51:41.689172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473aa203d910'
down_revision = '4d872a008e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
